const LOADING = 'LOADING'
const LOGIN = 'LOGIN'
const LOG_OUT_USER = 'LOG_OUT_USER'
const RESET_PASSWORD = 'RESET_PASSWORD'
const RESET_PASSWORD_COMPLETED = "RESET_PASSWORD_COMPLETED"
const RESET_PASSWORD_PERIOD_EXPIRED = "RESET_PASSWORD_PERIOD_EXPIRED"
const PASSWORD_RESET_EMAIL_RESENT = "PASSWORD_RESET_EMAIL_RESENT"
const CREATE_POTENTIAL_WORKOUT = "CREATE_POTENTIAL_WORKOUT"
const CLEAR_POTENTIAL_WORKOUT = "CLEAR_POTENTIAL_WORKOUT"
const GET_PREVIOUS_POTENTIAL_EXERCISE = "GET_PREVIOUS_POTENTIAL_EXERCISE"
const GET_NEXT_POTENTIAL_EXERCISE = "GET_NEXT_POTENTIAL_EXERCISE"
const SET_WORKOUT_QUESTION_RESPONSES = "SET_WORKOUT_QUESTION_RESPONSES"
const ADD_WORKOUT = "ADD_WORKOUT"
const CLEAR_WORKOUT_QUESTION_RESPONSES = "CLEAR_WORKOUT_QUESTION_RESPONSES"
const LOADING_COMPLETE = "LOADING_COMPLETE"
const CREATE_NEW_WORKOUT = "CREATE_NEW_WORKOUT"
const SET_NEXT_POTENTIAL_EXERCISE = "SET_NEXT_POTENTIAL_EXERCISE"

export { LOADING, LOADING_COMPLETE, CLEAR_WORKOUT_QUESTION_RESPONSES, SET_WORKOUT_QUESTION_RESPONSES, ADD_WORKOUT, LOGIN, LOG_OUT_USER, RESET_PASSWORD, RESET_PASSWORD_COMPLETED, RESET_PASSWORD_PERIOD_EXPIRED, PASSWORD_RESET_EMAIL_RESENT, CREATE_POTENTIAL_WORKOUT, CLEAR_POTENTIAL_WORKOUT, GET_PREVIOUS_POTENTIAL_EXERCISE, GET_NEXT_POTENTIAL_EXERCISE, SET_NEXT_POTENTIAL_EXERCISE, CREATE_NEW_WORKOUT }

