const LOADING = 'LOADING'
const LOGIN = 'LOGIN'
const LOG_OUT_USER = 'LOG_OUT_USER'
const RESET_PASSWORD = 'RESET_PASSWORD'
const RESET_PASSWORD_COMPLETED = "RESET_PASSWORD_COMPLETED"
const RESET_PASSWORD_PERIOD_EXPIRED = "RESET_PASSWORD_PERIOD_EXPIRED"
const PASSWORD_RESET_EMAIL_RESENT = "PASSWORD_RESET_EMAIL_RESENT"

export { LOADING, LOGIN, LOG_OUT_USER, RESET_PASSWORD, RESET_PASSWORD_COMPLETED, RESET_PASSWORD_PERIOD_EXPIRED, PASSWORD_RESET_EMAIL_RESENT }