const LOADING = 'LOADING'
const LOGIN = 'LOGIN'
const LOG_OUT_USER = 'LOG_OUT_USER'
const RESET_PASSWORD = 'RESET_PASSWORD'
const RESET_PASSWORD_COMPLETED = "RESET_PASSWORD_COMPLETED"

export { LOADING, LOGIN, LOG_OUT_USER, RESET_PASSWORD, RESET_PASSWORD_COMPLETED }